### ISSUE TITLE
UX wireframe 

### ISSUE THREAD

**Issue by Swaraj-Singh-30** [ykdojo/defaang#10]
Here is the UX wireframe for the website, if ready to got with it will be issuing an UI too. 

https://excalidraw.com/#json=R6Dr_C1S9JMKNl1lKVdkZ,5Cpg-gVKd0mzRfLXUfz9aA

**Comment by ykdojo** [comment]
Wow amazing! Really appreciate you doing this, @Swaraj-Singh-30.

Questions:

1. What's the alumni section for?
2. Any chance we can have something simpler to get started with so it's easier for everyone to implement it?

Thank you so much again!

**Comment by Swaraj-Singh-30** [comment]
Alumni section is for the people who have tried the project and has given feedback. We can just post it: like if it can be a tweet , an IG post or soo

Regarding the easier version, YES I will make one 

One thing @ykdojo IF you can tell me specifically we part you want simpler. For example like a simpler version of hero-banner, content page, Question and solution page or so....

Actually we can also do one-by-one. Will work on one page then on the another one.

What's your take YK? Please let me know what do you think about it 😄

**Comment by ykdojo** [comment]
Yes! One by one sounds good.

The first step is the signup flow as I mentioned at #14, and then after that, maybe a submission box? We can store them privately for now (probably in Supabase or Firebase), and once we have a few, we can make a view for showing those questions.

**Comment by ykdojo** [comment]
Closing this as I think @Swaraj-Singh-30's going to be busy for a while.

**Comment by yaa-chi** [comment]
> Here is the UX wireframe for the website, if ready to got with it will be issuing an UI too.
> 
> https://excalidraw.com/#json=R6Dr_C1S9JMKNl1lKVdkZ,5Cpg-gVKd0mzRfLXUfz9aA

@Swaraj-Singh-30  this is amazing! I love it! But what about the sign-up/login-in page? Should I create that?

**Comment by ykdojo** [comment]
@yaa-chi you should!

keep in mind we already have #88

**Comment by Swaraj-Singh-30** [comment]
> > Here is the UX wireframe for the website, if ready to got with it will be issuing an UI too.
> > https://excalidraw.com/#json=R6Dr_C1S9JMKNl1lKVdkZ,5Cpg-gVKd0mzRfLXUfz9aA
> 
> @Swaraj-Singh-30 this is amazing! I love it! But what about the sign-up/login-in page? Should I create that?

Yes! Actually while making the wireframe I had to totally forgotten about login page. 

You can check out #14

**Comment by Swaraj-Singh-30** [comment]
In

> > Here is the UX wireframe for the website, if ready to got with it will be issuing an UI too.
> > https://excalidraw.com/#json=R6Dr_C1S9JMKNl1lKVdkZ,5Cpg-gVKd0mzRfLXUfz9aA
> 
> @Swaraj-Singh-30 this is amazing! I love it! But what about the sign-up/login-in page? Should I create that?

Yes! Actually while making the wireframe I had totally forgotten about login page.

You can check out #14 too

**Comment by yaa-chi** [comment]
> In
> 
> > > Here is the UX wireframe for the website, if ready to got with it will be issuing an UI too.
> > > https://excalidraw.com/#json=R6Dr_C1S9JMKNl1lKVdkZ,5Cpg-gVKd0mzRfLXUfz9aA
> > 
> > 
> > @Swaraj-Singh-30 this is amazing! I love it! But what about the sign-up/login-in page? Should I create that?
> 
> Yes! Actually while making the wireframe I had totally forgotten about login page.
> 
> You can check out #14 too

Sure, will check it out now⚡
