### ISSUE TITLE
[FEATURE] A question submission box (backend)

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#108]
### Description

This is the backend portion of #59.

**Comment by ykdojo** [comment]
The first step for this task: design the database schema.

**Comment by ykdojo** [comment]
I'm going to start working on this one soon.

**Comment by ykdojo** [comment]
Users table:

![Image](https://user-images.githubusercontent.com/1811651/185769124-7c06affa-60fe-4836-a70d-f774b9cacf03.png)

**Comment by ykdojo** [comment]
I'm going to un-assign myself since I'll be away - in case anyone else wants to take it. I'll assign myself when I start working on it again.

**Comment by ykdojo** [comment]
From my own comment on #59:

The required fields:

- Company (FAANG+, or a custom textbox)
- Location
- Date (how long ago was this asked?)
- Question (100 char max?)
- Question details
- Stay anonymous (checkbox)

**Comment by ykdojo** [comment]
For the question table, this setup should be replicated:

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/1811651/185810627-d3906ebd-0531-4b0f-b7ce-54b876023c4a.png">

created_by is a foreign key to the auth.users table.

<img width="650" alt="image" src="https://user-images.githubusercontent.com/1811651/185810676-aa734167-9a74-44a9-8b01-9b22d0113280.png">

**Comment by ykdojo** [comment]
A rough plan for this feature:

- Assumption: a user is already logged in
- Frontend: the user submits a question
- It goes to an API function within Next.js / Vercel
- We verify that the user is logged in there (pass a JWT there)
- It then calls Supabase with admin access
- The question is inserted in the table.

This whole process may seem a bit complicated, but I think this is the right way to do it to make it as secure as possible.

I've even thought about switching to Firebase because it's complicated, but the workflow with it would be essentially the same.

There may be other ways of going about it (e.g., using row level security / RLS), but the above approach should be the simplest one. I'll document everything as I go here.

**Comment by ykdojo** [comment]
Documentation references:

- [Next.js API routes](https://nextjs.org/docs/api-routes/introduction)
- [Vercel serverless functions](https://vercel.com/docs/concepts/functions/serverless-functions)
- [Supabase passing JWT](https://github.com/supabase/supabase/issues/147#issuecomment-687579946)
- [Getting JWT](https://github.com/supabase/supabase/discussions/4312)

(Extra - thinking of sending a PR to update the Supabase doc [here](https://supabase.com/docs/reference/javascript/auth-user) once I'm done with this whole process)

**Comment by ykdojo** [comment]
I did some more research on this.

- [How to store JWT in a HTTP-only cookie securely](https://stackoverflow.com/questions/27067251/where-to-store-jwt-in-browser-how-to-protect-against-csrf#:~:text=In%20web%20browser%2C%20you%20can,it%20will%20not%20help%20you.) (this is probably the right approach)
- [A reference on React forms](https://reactjs.org/docs/forms.html)
- [One more reference page on Next.js API](https://nextjs.org/learn/basics/api-routes/api-routes-details)

**Comment by ykdojo** [comment]
Using fetch to set authorization header: https://reqbin.com/code/javascript/ricgaie0/javascript-fetch-api-example

**Comment by ykdojo** [comment]
update: [verified that `supabase.auth.session().access_token` worked](https://github.com/supabase/supabase/discussions/4312) for getting the JWT.

next step: set up a Next.js API and send it there.

**Comment by ykdojo** [comment]
note: the current user can be retrieved with `supabase.auth.user()`

**Comment by ykdojo** [comment]
I'm going to unassign myself for now to work on https://github.com/ykdojo/defaang/issues/122 first.

**Comment by iShibi** [comment]
I can pick the work from here

**Comment by ykdojo** [comment]
@iShibi sure! That'd be great.

**Comment by ykdojo** [comment]
Note: we should add a position field to the table.

**Comment by ykdojo** [comment]
@iShibi any progress? If not, I was thinking of working on this one

**Comment by iShibi** [comment]
Didn't get time to start the work, you can take it @ykdojo

**Comment by ykdojo** [comment]
I'll let you know if/when I start working on it

**Comment by ykdojo** [comment]
updated schema:

![Image](https://user-images.githubusercontent.com/1811651/186947010-6eb9431d-17f1-4426-9eed-b57846afac2d.png)

**Comment by ykdojo** [comment]
reference: [supabase insert](https://supabase.com/docs/reference/javascript/insert)

**Comment by ykdojo** [comment]
note on supabase service role: https://github.com/supabase/supabase/discussions/1284

**Comment by ykdojo** [comment]
After some more digging, I found that Supabase has a Next.js auth component - I'll look into this one next: https://github.com/supabase/auth-helpers/blob/main/packages/nextjs/README.md

**Comment by ykdojo** [comment]
I thought [this](https://supabase.com/docs/reference/javascript/auth-setauth) might work, but it doesn't quite work the way it's described in the doc.

**Comment by ykdojo** [comment]
[This one](https://github.com/supabase/supabase/issues/147#issuecomment-949953227) worked!

**Comment by ykdojo** [comment]
Note: I'm currently checking [this example](https://github.com/vercel/next.js/tree/canary/examples/with-supabase-auth-realtime-db) to see how they solved it.

**Comment by ykdojo** [comment]
I've found [this comment](https://github.com/supabase/supabase/discussions/1094#discussioncomment-587587) to be helpful, too.

**Comment by subhoghoshX** [comment]
I wrote an SQL query to generate the above table automatically if anyone here doesn't want to do it manually every time. Just go to the SQL Editor tab in supabase and run the query.

If you find any mistake in the query below, please let me know.

```sql
-- Create a table for Public Profiles
create table profiles (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references auth.users(id) not null,
  company text,
  location text,
  asked_date date,
  question text,
  question_details text,
  stay_anonymous boolean,
  is_approved boolean,
  position text
);
```

**Comment by ykdojo** [comment]
update: I'll be working off of [this draft PR](https://github.com/ykdojo/defaang/pull/137)
