### ISSUE TITLE
[DX] <Clean up the root directory>

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#113]
### Description

The root directory has many dotfiles and config files, and it's not a very pleasant experience.

We should clean up some of them so it's easier to get started contributing to this repo.

**Comment by AakashRaj20** [comment]
> ### Description
> 
> The root directory has many dotfiles and config files, and it's not a very pleasant experience.
> 
> We should clean up some of them so it's easier to get started contributing to this repo.

Hey @ykdojo I would like to try this issue can you assign this to me 😄

**Comment by benny123tw** [comment]
We can put `.lintstagedrc` and `.commitlintrc.json` in our `package.json`.

See:
1. https://github.com/okonet/lint-staged#Configuration
2. https://github.com/conventional-changelog/commitlint#config

**Comment by AakashRaj20** [comment]
> ### Description
> The root directory has many dotfiles and config files, and it's not a very pleasant experience.
> 
> We should clean up some of them so it's easier to get started contributing to this repo.

Hey @ykdojo I wanted to ask that should I make a new folders for dotfiles and config files and move them to their respective folders?

**Comment by ykdojo** [comment]
@AakashRaj20 yes that might work well. Just make sure that these dotfiles work even if they're put in folders.

**Comment by AakashRaj20** [comment]
> @AakashRaj20 yes that might work well. Just make sure that these dotfiles work even if they're put in folders.

ok will do that

**Comment by AakashRaj20** [comment]
> @AakashRaj20 yes that might work well. Just make sure that these dotfiles work even if they're put in folders.

Hey I have moved all the dot files in a separate folder and as there are only 3 config files, so I guess it will not be needed should I raise a PR so that you can have a look?

**Comment by ykdojo** [comment]
Did you test it?

**Comment by AakashRaj20** [comment]
> Did you test it?

Yes it's working fine

**Comment by ykdojo** [comment]
Great. When you open the PR, do you mind explaining how you tested each file you moved?

**Comment by veganaize** [comment]
_Note: Addresses #113_

**Comment by AakashRaj20** [comment]
> Great. When you open the PR, do you mind explaining how you tested each file you moved?
So actually for testing I launched the website in my local machine and everything was working fine, so can you guide me on how can perform specific test for each file?

**Comment by ykdojo** [comment]
@AakashRaj20 I didn't create some of the files, so could you find the person who created each one and ask them?

**Comment by AakashRaj20** [comment]
> @AakashRaj20 I didn't create some of the files, so could you find the person who created each one and ask them?

Ok will do so

**Comment by iShibi** [comment]
Closing this as config files are supposed to be in the root directory for them to work. The other ways of "hiding" them are not very worth it which include polluting `package.json` and editor-specific features.
