### ISSUE TITLE
[DOCS] <Remove the part about issue labels>

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#118]
### Description

From Contributing.md:

There are three categories of issues on the defaang GitHub issue tracker:

1. **Bugs** come in two flavours: non-critical and critical. Non-critical bugs are those that sometimes can mean a nuisance but that do not seriously affect working with the app. Critical bugs, however, make the app barely or un-usable, and fixes need to be addressed urgently.
2. **Enhancements** are some small additions that require adding some more functionality to a feature, but that should not evolve into an own distinct feature. Even if the issue description reads like a full feature to you, the "enhancement" label means there is already said functionality, which just needs to be amended. Please ask if you are unsure.
3. **Features** are bigger additions to the application that require a completely new feature.

I don't think we use these labels yet - so we should probably remove this section until/unless we do.

**Comment by benny123tw** [comment]
Hi @ykdojo, can I do this issue? I'll remove the section `Issue Labels` and use Grammarly to improve some sentences.

**Comment by ykdojo** [comment]
Yes! Thank you @benny123tw
