### ISSUE TITLE
[FEATURE] <Create a header bar with Tailwind UI>

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#122]
### Description

We can probably just use [simple dark](https://tailwindui.com/components/application-ui/navigation/navbars#component-1f0fd3139f66c75457637ca3746e3384).

Create a header bar with a login/signup link.

If the user is already logged in, we should show the user's info - (part of) the email address for now.

**Comment by omkarg01** [comment]
Hi @ykdojo, I would like to work on this issue.

**Comment by ykdojo** [comment]
Cool! Let me know if you need the code for the UI component

**Comment by omkarg01** [comment]
> Cool! Let me know if you need the code for the UI component

Yeah, need a code for that component

**Comment by ykdojo** [comment]
^if that doesn't work, we might need to try another component - just let me know

**Comment by ykdojo** [comment]
@omkarg01 any progress? If not, I might start working on this soon.

**Comment by omkarg01** [comment]
Yes @ykdojo I'm working on it

**Comment by omkarg01** [comment]
Header added
![heaeder added](https://user-images.githubusercontent.com/67428719/186959429-3e94d38e-fcea-433f-b3cc-8e7615bdcb33.png)

@ykdojo how can I go about the next step?

**Comment by ykdojo** [comment]
I'm actually working on handling auth at #132.

For now, can you send a draft PR or a regular PR of what you have so far?
