### ISSUE TITLE
[DX] <Remove the commit message restriction on Husky>

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#125]
### Description

I think we should remove the commit message restriction on Husky.

I get the value of conventional commit messages, but most commits shouldn't show up anyway as long as we squash and merge PRs.

So, as long as the commits on the main branch have the proper format, individual commit messages shouldn't matter so much.

**Comment by benny123tw** [comment]
This is great! And maybe we could use [GitHub Action](https://github.com/marketplace/actions/commit-linter) to run commit lint when PR is triggered?

**Comment by ykdojo** [comment]
That sounds good!

**Comment by benny123tw** [comment]
Hi @ykdojo, Can I do this issue? I'll remove `commitlint` packages and husky hook `commit-msg`. 

I did some tests on GitHub Action I realized that running commit lint on pull requests is the same as we use it locally; it will check all the commits.
I think we just need a [PR title checker](https://github.com/thehanimo/pr-title-checker) to check the title, so I'll add a workflow to use [PR title checker](https://github.com/thehanimo/pr-title-checker). What do you think?

**Comment by ykdojo** [comment]
Yes that sounds perfect! Thank you @benny123tw
