### ISSUE TITLE
[FEATURE] <A question submission box> (styling)

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#127]
### Description

As I recently asked on [Tailwind UI's discord](https://discord.com/invite/KeGhzt4), I have a styling issue for #59 with [this Tailwind UI component](https://tailwindui.com/components/application-ui/forms/form-layouts#component-30dffb06e58cdbe872820ed3f943d85a).

<img width="932" alt="image" src="https://user-images.githubusercontent.com/1811651/186504280-8f1c9274-8836-494a-8fa3-32fc95431305.png">

**Comment by ykdojo** [comment]
Note: looks like these two commits fixed almost everything except for a few minor font differences:

https://github.com/ykdojo/defaang/commit/384436e0874019648c1258c8172f301e2c9165db
https://github.com/ykdojo/defaang/commit/9d1d8cdc962cade242d282a8fca013404d0111d3

**Comment by subhoghoshX** [comment]
> Note: looks like these two commits fixed almost everything except for a few minor font differences:
> 
> [384436e](https://github.com/ykdojo/defaang/commit/384436e0874019648c1258c8172f301e2c9165db) [9d1d8cd](https://github.com/ykdojo/defaang/commit/9d1d8cdc962cade242d282a8fca013404d0111d3)

Could you please elaborate on what font differences you're experiencing?

**Comment by ykdojo** [comment]
It's not a huge deal, but the font looks slightly different:

![image](https://user-images.githubusercontent.com/1811651/186733349-d0e2f120-f964-4b00-8050-8d36edb4d6d1.png)

**Comment by ykdojo** [comment]
the fonts look slightly different, though?
![image](https://user-images.githubusercontent.com/1811651/186737102-88a807d2-8c61-400b-8551-e4d3d38ac4cd.png)
![image](https://user-images.githubusercontent.com/1811651/186737125-1e8a3a6d-c117-4832-ad87-9edc6dc6734f.png)

**Comment by subhoghoshX** [comment]
> the fonts look slightly different, though? ![image](https://user-images.githubusercontent.com/1811651/186737102-88a807d2-8c61-400b-8551-e4d3d38ac4cd.png) ![image](https://user-images.githubusercontent.com/1811651/186737125-1e8a3a6d-c117-4832-ad87-9edc6dc6734f.png)

Oh no, that's an entirely different font-family. Let me dig into it.

**Comment by subhoghoshX** [comment]
I ended up asking Adam Wathan, the creator of TailwindCSS.

![image](https://user-images.githubusercontent.com/108616679/186747366-f6c75e7d-b62c-4776-a983-d01c3f9afc08.png)

Essentially we need to add this:

```css
html {
    font-feature-settings: 'cv03','cv04','cv11';
}
```

**Comment by ykdojo** [comment]
cool!

so we just need to add that in global css right?

**Comment by subhoghoshX** [comment]
Yes. I think the base layer in TailwindCSS would be an appropriate place to add it.

Let me send a PR.
