### ISSUE TITLE
[FEATURE] <Make a signup/login view>

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#14]
### Description

The first step in terms of dev/coding for this project is, I think, the signup/login view.

Signing up will be useful in case people want to associate their submission with their email address. In my opinion, it's important for people to have that option so that if the submission is not complete, we can go back and forth to make sure it's in a good enough state for us to feature on the website.

**Comment by Swaraj-Singh-30** [comment]
Will give it try. Tech will be simple HYML, CSS and JS

**Comment by ykdojo** [comment]
@Swaraj-Singh-30 sounds good - thank you so much!!

**Comment by VaibhavSinghDev** [comment]
Do you want the front end for login and signup?

**Comment by ykdojo** [comment]
Yes! @Swaraj-Singh-30 might be making it though, I'm not sure.

**Comment by khanhtranngoccva** [comment]
How about ReactJS though @ykdojo? I have never seen projects with both plain-JS and ReactJS before. 😅

**Comment by ykdojo** [comment]
Yes it'll be ideal to have it in React / Next.

But if someone submits something in plain JS, I think we can still use parts of it, especially if it uses Tailwind (which we're planning to use for this)

**Comment by ykdojo** [comment]
@Swaraj-Singh-30 feel free to give it a try! we can convert it to Next.js + Tailwind later, too

**Comment by Swaraj-Singh-30** [comment]
Okay Yk 👍🏻🔥

**Comment by promisethedeveloper** [comment]
@ykdojo for the signup/logic form, would you want the user's information stored in a database yet? Or do you want the signup/login form without that functionality for now?

**Comment by ykdojo** [comment]
Yes! We should start storing that info.

I think I’ll set up an account and a database in Supabase soon assuming we’ll go with it: https://github.com/ykdojo/defaang/discussions/23

But anyone can set up their own instance, and assuming it looks good, I can replicate that in my account, too.

**Comment by ykdojo** [comment]
A bit more info on what's to come next: https://github.com/ykdojo/defaang/issues/10#issuecomment-1212334602

**Comment by Jonyango** [comment]
@Swaraj-Singh-30 @ykdojo I am familiar with Next.js and tailwind, and if you haven't started building, I can pick it up or provide some guidance.

**Comment by Swaraj-Singh-30** [comment]
Can you convert it into Next.js and tailwind?

**Comment by Jonyango** [comment]
> Can you convert it into Next.js and tailwind?

Yes

**Comment by jideabdqudus** [comment]
I'll like to build the SignUp/Login using NextJS and AntD. Would this be a preferable stack?

**Comment by Preet-Sojitra** [comment]
In my opinion first we should make only UI in Figma or any other software, if it gets approved, then we should code it, cause once the design is finalized then it will be more easy to code it.

**Comment by Swaraj-Singh-30** [comment]
> In my opinion first we should make only UI in Figma or any other software, if it gets approved, then we should code it, cause once the design is finalized then it will be more easy to code it.

I'm working on it from yesterday, will publish it.

**Comment by ykdojo** [comment]
> I'll like to build the SignUp/Login using NextJS and AntD. Would this be a preferable stack?

any reason to use AntD over Tailwind?

**Comment by ykdojo** [comment]
Note: now that #28 is merged, we should be able to use that as a starting point for this issue.

**Comment by jideabdqudus** [comment]
> > I'll like to build the SignUp/Login using NextJS and AntD. Would this be a preferable stack?
> 
> any reason to use AntD over Tailwind?

Suggested AntD because of the amount of readily made components that could be used, Tailwind works too. But it's a preference

**Comment by Karthik-315** [comment]
Would it be ok, if I submit here, a Figma design for login / sign-up, here? I see that @Swaraj-Singh-30 is working on it, so don't want to interfere...

**Comment by ykdojo** [comment]
Yes! I think @Swaraj-Singh-30 is working on a plain JS version, so it's ok to have a Figma, too

**Comment by Karthik-315** [comment]
Cool! So here's a rough design I made: [Figma Design](https://www.figma.com/file/uYiv3KebAnh7n60Ifz2UJ2/Defaang-Sign-In-%2F-Sign-Up?node-id=0%3A1). I've put in Login and Sign up in separate pages. 

Take a look and feel free to let me know your suggestions. Also, if you need access to the file, let me know.

**Comment by Preet-Sojitra** [comment]
> Cool! So here's a rough design I made: [Figma Design](https://www.figma.com/file/uYiv3KebAnh7n60Ifz2UJ2/Defaang-Sign-In-%2F-Sign-Up?node-id=0%3A1). I've put in Login and Sign up in separate pages.
> 
> Take a look and feel free to let me know your suggestions. Also, if you need access to the file, let me know.
> 
> Edit: Added a dummy placeholder logo, that can be changed later.

Looks good 👍

**Comment by Sanskar-khandelwal** [comment]
> Cool! So here's a rough design I made: [Figma Design](https://www.figma.com/file/uYiv3KebAnh7n60Ifz2UJ2/Defaang-Sign-In-%2F-Sign-Up?node-id=0%3A1). I've put in Login and Sign up in separate pages.
> 
> Take a look and feel free to let me know your suggestions. Also, if you need access to the file, let me know.
> 
> Edit: Added a dummy placeholder logo, that can be changed later.

Hey, everything looks super good, just a  suggestion that back sign, Can be a little thin, try using a iconify icon instead of that

**Comment by Karthik-315** [comment]
> > Cool! So here's a rough design I made: [Figma Design](https://www.figma.com/file/uYiv3KebAnh7n60Ifz2UJ2/Defaang-Sign-In-%2F-Sign-Up?node-id=0%3A1). I've put in Login and Sign up in separate pages.
> > Take a look and feel free to let me know your suggestions. Also, if you need access to the file, let me know.
> > Edit: Added a dummy placeholder logo, that can be changed later.
> 
> Hey, everything looks super good, just a suggestion that back sign, Can be a little thin, try using a iconify icon instead of that

Fair point, I've changed it with a slimmer one. Thanks for your suggestion!

**Comment by ykdojo** [comment]
Looks good! I feel like we can experiment with different colors, though.

Also, I was thinking we can start with a light mode so it's more welcoming to everyone. What do you think?

**Comment by Preet-Sojitra** [comment]
Yes starting with light mode is good idea, then at later stage we can add functionality of switching between dark and light mode

**Comment by Karthik-315** [comment]
Noted your points, will design for light mode too.

**Comment by Karthik-315** [comment]
Apart from color scheme, does anything else needs improvising, you think? Like the form elements?

**Comment by Karthik-315** [comment]
Apart from color scheme, what is your opinion on the other elements,  like the form elements and such, looks good?

**Comment by Swaraj-Singh-30** [comment]
Hello folks this is to inform y'all that since I won't be able to complete the login/sign up part, somebody else can take the part.

**Comment by ykdojo** [comment]
@Karthik-315 I think everything else looks good!

**Comment by jideabdqudus** [comment]
> Hello folks this is to inform y'all that since I won't be able to complete the login/sign up part, somebody else can take the part.

What's the update on this? Is anyone working on it or I can pick it up?

**Comment by jideabdqudus** [comment]
> Cool! So here's a rough design I made: [Figma Design](https://www.figma.com/file/uYiv3KebAnh7n60Ifz2UJ2/Defaang-Sign-In-%2F-Sign-Up?node-id=0%3A1). I've put in Login and Sign up in separate pages.
> 
> Take a look and feel free to let me know your suggestions. Also, if you need access to the file, let me know.
> 
> Edit: Added a dummy placeholder logo, that can be changed later.

Looks good mate, one thing I'll like to confirm is why is there a back sign on the auth screen, (especially on desktop mode) where does clicking on back lead to?

**Comment by Karthik-315** [comment]
The back button is just another way to navigate to the home page. 

I think based on the design of the landing page, this can be removed, if there is a link to redirect to home page on the Navbar.

**Comment by ykdojo** [comment]
Sounds good - I'm not sure about navbar, though. (No strong opinion either way right now)

**Comment by SrPanquesito** [comment]
Hello. I would like to contribute to the UI in this part as well.

@jideabdqudus  can we work together on it?

**Comment by ykdojo** [comment]
Cool! Keep in mind that there's this open PR, too: #64 

But pls feel free to contribute where you see fit!

**Comment by SrPanquesito** [comment]
> Cool! Keep in mind that there's this open PR, too: #64
> 
> But pls feel free to contribute where you see fit!

Thanks. I've just cloned his repo and saw the changes. It seems he's following a different design from the proposed one in this thread.

I was thinking about following the [Figma Design](https://www.figma.com/file/uYiv3KebAnh7n60Ifz2UJ2/Defaang-Sign-In-%2F-Sign-Up?node-id=0%3A1) but should I wait for his PR to be merged?

**Comment by ykdojo** [comment]
Following the Figma design sounds good. #64 is good for now since we don't have a logo yet, though. It'll probably also needs some refining, too.

I think one option is to fork that PR and start making some progress there? Then once #64 is merged, then you can send your PR?

**Comment by Karthik-315** [comment]
I've also added a light mode option to the design.

 If we all agree on a different color scheme later, this can be changed.

**Comment by vrindavan** [comment]
Hey, is there anyone working on a Dark Mode right now?

**Comment by ykdojo** [comment]
@vrindavan I don't think so? Unless @Karthik-315 is

Also we should decide on a dark mode color palette at #82

**Comment by ykdojo** [comment]
I'm going to close this for now since we have working signup/login views.
