### ISSUE TITLE
[FEATURE] <Improve Header Menu Component>

### ISSUE THREAD

**Issue by subhoghoshX** [ykdojo/defaang#148]
### Description

This is related to #140.

Right now the Menu component used in the Header doesn't show the user's email on the desktop screen when logged in. It only shows on mobile screens.

I think this [component](https://tailwindui.com/components/application-ui/elements/dropdowns#component-1f7aa0b082c3b5074c78634c7d29588e) might be a better fit which also shows the email similar to how GitHub does it.

**Comment by mark-omarov** [comment]
Since nobody is currently assigned, let me take this.

**Comment by subhoghoshX** [comment]
Haha, I was implicitly assigned to this as it's related to #140. But you can do it if you want.

**Comment by mark-omarov** [comment]
@subhoghoshX sorry, wasn't aware.
I'm not getting much time recently for oss, wanted to do at least something while got a few minutes to spare 😄
The PR is ready, feel free to check it out. If any updates necessary - will be able to update no earlier than by this Friday, sorry 🥲

**Comment by subhoghoshX** [comment]
No problem :smile:  I'm afraid this might cause a merge conflict with my other PR #147. But I guess I'll just resolve it after merging yours.

**Comment by mark-omarov** [comment]
@subhoghoshX if it's too much hustle, we can do the other way around - once you merge your PR, I'll rebase, fix conflicts, and update my PR. Unfortunately, it might wait until Friday, although, if it's ready by tomorrow, I might be able to get it done in the evening (JST time). I'll leave it up to you to decide what's best.

**Comment by subhoghoshX** [comment]
No worries already merged it. It's nothing critical to wait that long. And the conflict is also pretty easy to resolve.

Thanks for working on it.

**Comment by mark-omarov** [comment]
My pleasure. Thanks for taking a look and merging! ❤️
