### ISSUE TITLE
[FEATURE] <Show avatar in Header instead of name>

### ISSUE THREAD

**Issue by subhoghoshX** [ykdojo/defaang#156]
### Description

This is related #140.

I was thinking that we should go back to showing avatar in the Header instead of name. At least show a default avatar for now.

Showing an avatar is the most common pattern. And also when the size of the name varies too much it makes the design look bad.

Would love to know everyone's opinion on this.

**Comment by mark-omarov** [comment]
I tend to agree, it's also not very intuitive that the name is a menu button. Avatar seems more appropriate to me.

**Comment by subhoghoshX** [comment]
> I tend to agree, it's also not very intuitive that the name is a menu button. Avatar seems more appropriate to me.

Definitely agree with you.

@mark-omarov would you like to take a stab at it? Feel free to go for it if you wanna do it.

**Comment by subhoghoshX** [comment]
> I tend to agree, it's also not very intuitive that the name is a menu button. Avatar seems more appropriate to me.

Definitely agree with you.

@mark-omarov would you like to take a stab at it? Feel free to go for it if you wanna do it. Here's the [code](https://github.com/ykdojo/defaang/issues/122#issuecomment-1225804022) for the Header.

**Comment by mark-omarov** [comment]
@subhoghoshX sure, weekends ahead, will be able to get at it.

**Comment by yung-coder** [comment]
@subhoghoshX are you saying for a random profile pic when user sign up ...?

**Comment by mark-omarov** [comment]
@yung-coder we don't have avatars per se just yet, I'll be adding a default avatar-like icon button, which later on will be enhanced with a custom avatars uploaded through settings.

**Comment by yung-coder** [comment]
I yeah have got idea with a random or custom avatar when a user sign up ...

**Comment by mark-omarov** [comment]
@subhoghoshX
I was playing with the avatar-like button, and when there's an actual image it looks fine, but with a placeholder (icon in our case) it doesn't look as good. How about we make the same format as the notification bell button, and once the user has a profile picture in the model - we can swap the icon to the rounded image instead?

<img width="262" alt="Screen Shot 2022-09-03 at 10 17 58 PM" src="https://user-images.githubusercontent.com/15357910/188272198-1c1c86f3-6bf7-4146-9b60-21ffd6e4058d.png">
