### ISSUE TITLE
[DOCS] Invalid Discord link in CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Gulshanaggarwal** [ykdojo/defaang#168]
### Description

**What's the problem?**
The Discord community Invite link is invalid in contributing.md file.

**See below image-**
<img width="908" alt="discord_invite_invalid" src="https://user-images.githubusercontent.com/58553401/189513903-84be17fb-7efb-423f-9a32-cbee0fe0faf8.png">

**How to reach to the problem?**

- Go to contributing.md file
- Click on the discord link mentioned under the **All Communication Channels**

**Comment by Gulshanaggarwal** [comment]
@ykdojo please verify it. I would like to start my first contribution in **defaang** by solving a simple docs fix.

**Comment by subhoghoshX** [comment]
Hey, @Gulshanaggarwal  thanks for pointing it out. Here's the working link `https://discord.gg/nNtVfKddDD`. Feel free to send a PR.

**Comment by Gulshanaggarwal** [comment]
Hey @subhoghoshX I have create the PR, check it out here -[#171]( https://github.com/ykdojo/defaang/pull/171)
