### ISSUE TITLE
[FEATURE] Create a new landing page where it shows more info about the website

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#172]
### Description

We should have a new landing page where we show more clearly what the website is about, and why people might want to submit a question.

The way it's going to work is:

We'll officially launch it when we have, say, 100 approved questions.

Until then, only people who have submitted at least one approved question should be able to see the other ones.

We should explain this on the landing page, and also show a progress bar at some point to show how many questions we have so far.

**Comment by ykdojo** [comment]
The tagline:

defaang - a website that will curate recently-asked interview questions from FAANG+ to help people practice & prep!

**Comment by ykdojo** [comment]
Or we could break it down into something like:

Where you can prep for your upcoming FAANG+ interviews.

We curate recently-asked interview questions from FAANG+ to help people practice & prep.

Inspirations:

https://www.landingfolio.com/inspiration/post/parallel
https://land-book.com/websites/38033-homerun-where-hiring-comes-together

**Comment by ykdojo** [comment]
Another inspiration - the gradient in [this landing page](https://tailwindui.com/) is pretty nice.

**Comment by ykdojo** [comment]
color: #82

**Comment by ykdojo** [comment]
gradient idea: https://tailwind-gradient-generator.vercel.app/gradient?colors=white-100,white-200,sky-300&direction=TR

**Comment by ykdojo** [comment]
I started to manually build this landing page, and then came across this template by Tailwind themselves: https://tailwindui.com/templates/salient

I'm considering buying it since I feel like it looks good enough for what we want.

**Comment by subhoghoshX** [comment]
> 

I don't think you need to buy another template. We won't even use most of it.

**Comment by subhoghoshX** [comment]
If I understand correctly I think we'll have something similar to this:

![image](https://user-images.githubusercontent.com/108616679/189721670-d653563d-ea54-44e8-a5d9-667a7ffb678d.png)

Then instead of having those two buttons, we can have an email input field. Something like this:

![image](https://user-images.githubusercontent.com/108616679/189721309-127d0a23-e38f-4455-addc-d0e3247feb9c.png)

**Comment by ykdojo** [comment]
@subhoghoshX yes something like that.

Instead of an email box, though, it might make sense to have Discord and GitHub links there for now.

**Comment by ykdojo** [comment]
![image](https://user-images.githubusercontent.com/1811651/189738768-0ca8b394-54de-42ba-a886-8959ac04308e.png)

**Comment by ykdojo** [comment]
work in progress:
![image](https://user-images.githubusercontent.com/1811651/189752933-ea528a63-271f-45ca-a90c-9f7bad164764.png)

**Comment by ykdojo** [comment]
What I have locally rn:
![image](https://user-images.githubusercontent.com/1811651/189792504-2f244c20-5bdf-41cf-a333-a17b070348fb.png)

![image](https://user-images.githubusercontent.com/1811651/189792515-db698b29-afc2-4e0f-b87e-a2f97005a894.png)

**Comment by ykdojo** [comment]
I had [this PR](https://github.com/ykdojo/defaang/pull/173) earlier, but I closed it for now so we can work on a fresh PR to send/review later.

**Comment by dattavelivela** [comment]
![image](https://user-images.githubusercontent.com/97103375/192211908-01cea057-1062-40d3-b981-2e9e9aef6f33.png)

Hello Folks, I have a query

I see that we have click action on How it works section. By clicking on contribute changes the color. 

I assume it is supposed to have a hyperlink in the future or it doesn't have any hyperlink?

**Comment by ykdojo** [comment]
I don't particularly have a strong opinion on either option, and I don't think this type of discussion should happen on a closed PR. Mind starting a Discussion around it if you'd like?
