### ISSUE TITLE
[DX] Database schema should be easily shareable

### ISSUE THREAD

**Issue by CerealPlayer** [ykdojo/defaang#180]
Using tools like Prisma as discussed in https://github.com/ykdojo/defaang/discussions/178 could help create a db schema that we can all use to bootstrap our Postgres databases. Many other use cases for it too.

This way we wouldn't need to jump to #108 every time we want to work with db

**Comment by ykdojo** [comment]
Why not just use a plain SQL for creating the db schema though?

**Comment by CerealPlayer** [comment]
While it is true, SQL might lead to vulnerabilities if not properly written.

**Comment by ykdojo** [comment]
Hmm it is really cool.

I don't have a strong preference either way though - so perhaps we can wait a bit to see if anyone else has any thoughts on it.

**Comment by ykdojo** [comment]
I was doing some research on this, and it turns out, Supabase even has an entire doc on how to set it up [here](https://supabase.com/docs/guides/integrations/prisma).

Seems pretty promising - I'll look into it.

**Comment by CerealPlayer** [comment]
Supabase doc's on this matter are pretty much Prisma doc's for every db.

That's another advantage I see. If anybody doesn't want to work with Supabase locally (personally I've run out of free projects) at least for the purely database stuff they can set up a Postgres docker container, bootstrap the same db using that schema plus Prisma migrate and use the Postgres connection string to connect to it the same way we would connect to Supa in prod.

**Comment by CerealPlayer** [comment]
Update

I started working on this but after going through the supabase.sql and looking at the cross schema references I can already say this will not work.
Prisma doesn't support cross schema referencing ([see here](https://github.com/prisma/prisma/issues/1175)) when introspecting databases, so unless we go for a different approach (such as handling auth on our own) we won't be able to use Prisma.
