### ISSUE TITLE
[DX] Convert components to tsx

### ISSUE THREAD

**Issue by CerealPlayer** [ykdojo/defaang#181]
### Description

Recently merged #179 introduced some components written in jsx. While that is not bad, we could transform them to tsx to align with the project stack and also improves future developments on those files.

If needed, I could work on that :)

**Comment by ykdojo** [comment]
Sure, that sounds like a good idea - thank you! Feel free to start working on it if you'd like.

**Comment by CerealPlayer** [comment]
Do we have any preference on how to handle types? I mean, should we have a types folder? Place types in an interface file alongside its component?

**Comment by ykdojo** [comment]
Answered this on my discord stream -

I don't have a strong preference for it, but I think it's good to start simple (in the same file or in an individual interface file), then extract the types into a separate folder/file once it gets too complex / we start reusing them.
