### ISSUE TITLE
[FEATURE] Company Tags(question submission form)

### ISSUE THREAD

**Issue by Gulshanaggarwal** [ykdojo/defaang#182]
### Description

To improve the user experience(UI & UX), I think we must give the option of company tags(initially for only a few companies), otherwise, user will write companies' names in different ways. for example - someone may write facebook or facebok. So it will make the other User's experience inconsistent because they will be seeing the same company name in different ways. And for reset of the companies, manually input is ok.

**Comment by Gulshanaggarwal** [comment]
@ykdojo  can I start working on this ?

**Comment by ykdojo** [comment]
How would you implement it?

**Comment by Gulshanaggarwal** [comment]
@ykdojo I will implement it something like what Leetcode does. As User types something, he/she will get a dropdown & can choose the company out from it. Initially we can avoid accepting names manually. Users will have to pick only from the dropdown list.

**Comment by ykdojo** [comment]
That sounds good.

How would you deal with a case when a company doesn't exist on this list yet?

Also, where would you store this list?

**Comment by Gulshanaggarwal** [comment]
@ykdojo Cool, If a company name not found we can allow user to manually type it or otherwise we can skip(like Leetcode). The list of companies can be stored in a json file over front end side or may be we can fetch from server side.

**Comment by ykdojo** [comment]
We should probably always have a way for users to use custom text for the company name, or create a new company tag, so we don't lose a user when they're trying to submit a question.

**Comment by subhoghoshX** [comment]
If the predefined companies are up to 5-10 then you can just use html `datalist`. No need to use any js or backend service.

**Comment by subhoghoshX** [comment]
If the predefined companies are up to 5-10 then you can just use html `datalist`. No need to use any js or backend service.

**Comment by Gulshanaggarwal** [comment]
> We should probably always have a way for users to use custom text for the company name, or create a new company tag, so we don't lose a user when they're trying to submit a question.

@ykdojo no problem, in that case we can ask for manually. I hope we are ready to implement it 🚀

**Comment by Gulshanaggarwal** [comment]
@subhoghoshX True 💯. I was just taking a case if we would have 50-100 companies, then we could store in json file or server side.

**Comment by ykdojo** [comment]
@Gulshanaggarwal sure, feel free to send a PR either as a regular PR or a draft one.

**Comment by Gulshanaggarwal** [comment]
Hey @ykdojo there is a problem with the Combobox  code. Actually with the combobox code it is difficult to maintain your state while taking advantage of react-form-hook. If I setup state manually without registering react-form-hook then only I'm able to take advantage of combobox. 
When I apply react-form-hook it's working. If you type something like **fac** it will show you the list & you can select but if you don't want select from the list & leave the cursor from the box then value on the screen get empty or either value you selected previously  will printed on the screen.

**Comment by Gulshanaggarwal** [comment]
Hey @ykdojo what do you think?

**Comment by ykdojo** [comment]
@Gulshanaggarwal got it.

What do you think of reverting back to your original implementation of simply using html `datalist` then?

**Comment by Gulshanaggarwal** [comment]
> @Gulshanaggarwal got it.
> 
> What do you think of reverting back to your original implementation of simply using html `datalist` then?

Yes, @ykdojo @subhoghoshX otherwise do you have any suggestions to make it more better than html datalist? I think html datalist are fine for now. Give me a shootup if you want me to revert it to html datalist.

**Comment by epicadidash** [comment]
@ykdojo we can use vanilla html and we can `usereducer()` for updating state

**Comment by ykdojo** [comment]
@epicadidash can you elaborate on what you mean exactly?

**Comment by subhoghoshX** [comment]
Hey, @Gulshanaggarwal if you're facing issues with combo boxes feel free to revert back. I'll try to implement the combo boxes when I've time.

**Comment by Gulshanaggarwal** [comment]
@subhoghoshX ok I will be sending a PR with old html datalist. If you can give a hint how you will take advantage of react-form-hook over comboboxes that would be a great help.

**Comment by Princeton21** [comment]
@Gulshanaggarwal what's the update on your issue?

**Comment by Gulshanaggarwal** [comment]
The solution I implemented was not so eye catching according to @ykdojo & although I implemented using Combobox but still a problem was here, I was not able to take advantage of react-hook-forms. So there is no updates after that.

**Comment by ykdojo** [comment]
I feel like we can go with the pure HTML solution for now since it seems easier to implement?

Then, later, we can switch to something that looks nicer if anyone wants to send a PR for that.

**Comment by Gulshanaggarwal** [comment]
Ok @ykdojo then let's go back with the html datalist again.
