### ISSUE TITLE
[DX] Add defaang to Hacktoberfest

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#193]
### Description

Figure out how to add it to Hacktoberfest and add it!

**Comment by Preet-Sojitra** [comment]
Here's what I found from Hacktoberfest website
https://hacktoberfest.com/participation/#maintainers 

So basically you have to add `hactoberfest` topic to the repo

**Comment by ykdojo** [comment]
From the Hacktoberfest website:

- Be ready to review pull/merge requests, accepting those that are valid by merging them, leaving an overall approving review, or by adding the “hacktoberfest-accepted” label.

- Reject any spammy requests you receive by labeling them as “spam,” and any other invalid contributions by closing them or labeling them as “invalid.”

**Comment by ykdojo** [comment]
For maintainers:

The hard work of our Maintainers is the reason Hacktoberfest exists, so we want you to have the opportunity to receive your very own Hacktoberfest 2022 reward. In order to become eligible for the opportunity to win a Reward Kit all a Maintainer will have to do is complete four or more maintainer actions on unique PR/MRs in repos participating in Hacktoberfest. Here are the Maintainer actions that qualify:

- Merge unique PR/MRs
- Provide an approving review of a PR/MR
- Add the “hacktoberfest-accepted” label
- Add any label with the word “invalid” or “spam”

*REWARD KITS ARE LIMITED; WE WILL REACH OUT TO QUALIFYING MAINTAINERS WHO ARE SELECTED TO RECEIVE A REWARD KIT AFTER HACKTOBERFEST ENDS.

**Comment by SanDiego2049** [comment]
Is this something anyone can do? If yes, then can i be assigned to it?

**Comment by ykdojo** [comment]
@SanDiego2049 I just double-checked it, and this one's actually already done. Feel free to look through the other issues, though.
