### ISSUE TITLE
[FEATURE] When a user is not signed in on the question submission page, redirect them to the sign up page

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#195]
### Description

Currently, they're redirected to the sign in page, but this should be the sign up page instead.

**Comment by ppborah** [comment]
I think `res.redirect.(200, '<signup api endpoint>')` should work.
Could you please let me know how do I get the signup api endpoint ?

**Comment by ivanolmo** [comment]
Hi @ykdojo, I'd like to work on this. I already have a working redirect and am ready to submit a PR.

**Comment by ppborah** [comment]
Hey @ivanolmo and @ykdojo, what is this `QuestionSubmissionForm.tsx` doing here👇 then ?

<img width="1319" alt="Screenshot 2022-09-23 at 11 05 40 AM" src="https://user-images.githubusercontent.com/96339995/191897908-c28879ef-c031-4eef-8bb3-639d907affbb.png">

**Comment by ivanolmo** [comment]
@ppborah It looks like the submit handler returns early and doesn't allow any submission if there is no valid session. I suppose that particular check is probably redundant if a valid session check is already performed in the parent page component.

**Comment by ppborah** [comment]
I get it now
Thanks :)
