### ISSUE TITLE
[BUG] Description: Application breaking in local environment

### ISSUE THREAD

**Issue by Gulshanaggarwal** [ykdojo/defaang#203]
### Description

What's the issue?
Because of the application breaking I created a fresh clone of the repo, & installed the dependencies again. After starting the server with **npm run dev** it starts the server but when I click on signup today buttonit doesn't take me there. If I type signup page url explicitly in my browser than it gives me the error.

### Screenshots

<img width="960" alt="defaang_error" src="https://user-images.githubusercontent.com/58553401/192140778-cbab4229-eba6-4ea3-96fb-71fc0efc8451.png">

**Comment by Gulshanaggarwal** [comment]
@ykdojo give a look at it

**Comment by ykdojo** [comment]
@Gulshanaggarwal did you add Supabase URL and API keys?

**Comment by Gulshanaggarwal** [comment]
@ykdojo I have already done with this. One more thing there is problem also on production side(just figured out). Goto[https://defaang.vercel.app/](https://defaang.vercel.app/) & click on signup today. If you already signed up then signin. Once you signin with your credentials, you will not be taken to the dashboard.

**Comment by ykdojo** [comment]
@Gulshanaggarwal what did you mean by the dashboard?

**Comment by Gulshanaggarwal** [comment]
> @Gulshanaggarwal what did you mean by the dashboard?

The page users see after signin.

**Comment by ykdojo** [comment]
@Gulshanaggarwal does it already exist in the current codebase? I'm just not sure what you mean by dashboard exactly.
