### ISSUE TITLE
[DOCS] Put Discord rules in a standalone file

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#205]
### Description

We should put our Discord rules in a standalone file here (say, DISCORD_RULES.md) so people can send suggestions as PRs.

Current rules:

1. Do not DM or call people without knowing them first.
2. If you have questions, ask them in public channels.

**Comment by epicadidash** [comment]
3.No use of inappropriate language or profanity should be kept to a minimum. However, any derogatory language towards any user is strictly prohibited.

**Comment by epicadidash** [comment]
4.No spamming i.e don't share the same message in every chat or keep repeating the message or pinging people for same request (message) again and again

**Comment by ykdojo** [comment]
@epicadidash did you write these by yourself or did you copy them from somewhere else?

**Comment by weilincheng** [comment]
Hi @ykdojo. I'd like to work on this issue as my first ever contribution to the open source project. I have filed a PR #206 for it. Would you please help take a look and let me know if I need to improve anything? Thanks a lot for providing the opportunity for someone who is entering the software engineering world. :)

**Comment by ykdojo** [comment]
@krshcodes and @epicadidash have more stuff to add to the discussion - we were just talking about it on our stream.

**Comment by epicadidash** [comment]
@ykdojo the rules are from my discord server

**Comment by ykdojo** [comment]
Let's not do any copy/pasting for the rules. I think it's important to come up with our own rules from scratch.
