### ISSUE TITLE
[FEATURE] Start using defaang.io instead of the vercel.app domain

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#211]
### Description

It'll be good to start using the io domain to make it look more official.

**Comment by Johnnyteck** [comment]
I'll suggest you update that in the README as well because I just clicked the link available on README and it's the vercel.app version

**Comment by ykdojo** [comment]
Update: updated this on Vercel.

**Comment by ykdojo** [comment]
Done. I put what @Johnnyteck mentioned in a separate issue here: #225.
