### ISSUE TITLE
[DX] Wrong Favicon !!!

### ISSUE THREAD

**Issue by epicadidash** [ykdojo/defaang#221]
### I would love to create a logo (Favicon) and implement it in code 
![image](https://user-images.githubusercontent.com/83776308/193062451-8eabd36f-81bd-472c-a31f-5d6c910a1c3c.png)

**Comment by epicadidash** [comment]
![defaang io (1)](https://user-images.githubusercontent.com/83776308/193317140-6296d785-f67c-4650-ba38-62ebfaf75867.jpg)

## A proposed logo

**Comment by epicadidash** [comment]
![Defaang](https://user-images.githubusercontent.com/83776308/193317545-a5bdd1d9-d251-46c9-97eb-a0a4f14565c7.jpg)
### A kind of logo but if accepted can be made into favicon

**Comment by ykdojo** [comment]
Let's discuss this at #224.

**Comment by Princeton21** [comment]
@ykdojo I feel this issue can be closed now.

**Comment by ykdojo** [comment]
@Princeton21 we should still change the favicon right? Or is it already fixed?

**Comment by Princeton21** [comment]
> @Princeton21 we should still change the favicon right? Or is it already fixed?

Yeah I guess it is fixed in #266 
and I felt that both issues #224 and this focus on the same problem
