### ISSUE TITLE
[DOCS] Change the demo link in README

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#225]
### Description

We should change the demo link on README from the Vercel link to defaang.io.

Related: #211

**Comment by Abhinav-J05** [comment]
Hey! I would like to contribute in this, Please assign this to me.

**Comment by ykdojo** [comment]
@Abhinav-J05, @AdityaPainuli sent a PR and it's closed already!

Feel free to take a look through other issues, though.
