### ISSUE TITLE
[DX] gitpodify repository

### ISSUE THREAD

**Issue by slim-codes** [ykdojo/defaang#237]
### Description

Add Gitpod button to **README.md** to rapidly open and use project without going through the hassle of forking, and cloning locally. Basic changes can be done quickly from the browser.

Click the button below to rapidly open the defaang workspace on through Gitpod in your browser

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/ykdojo/defaang)

**Comment by ykdojo** [comment]
@slim-codes just added a comment/question in your PR
