### ISSUE TITLE
[FEATURE] Add a Twitch link on the landing page

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#249]
### Description

It should be added here as a second CTA:

![image](https://user-images.githubusercontent.com/1811651/193957249-e7e38f6a-1673-4fe4-b7b7-c94aa8bfda4d.png)

The Twitch link is in README.

**Comment by kirtanchandak** [comment]
Can I work on this issue ?

**Comment by gauriimaheshwarii** [comment]
Hi, can I work on this issue?

**Comment by ykdojo** [comment]
@devXprite is working on it
