### ISSUE TITLE
[FEATURE] Must add loading/ popup for confirmation on Submit a Question page (https://defaang.vercel.app/questions/new)..

### ISSUE THREAD

**Issue by Akshay1018** [ykdojo/defaang#255]
### Description

We need to add a new feature for submitting a question. I tried to add the new question that was recently asked by Google and after clicking on submit button there is no success confirmation to the user. My suggestion is to add a popup or loading-on button for better user interaction.

**Comment by Akshay1018** [comment]
I will add this feature ASAP. If you don't mind, shall I take this issue?

**Comment by ykdojo** [comment]
There's a duplicate issue for this. Mind finding it and closing this one?

**Comment by Akshay1018** [comment]
Oops, my bad. I did'nt see this issue. You can close it. If you don't mind shall I take this feature to add?

**Comment by ykdojo** [comment]
@Akshay1018 sure, someone is already working on it, but we could have an alternative approach to that one.

**Comment by Akshay1018** [comment]
@ykdojo cool, So, shall I go ahead and work on it or you want me to hold and we can discuss some other alternative approach to fix this issue? I hope we are on the same page.

**Comment by ykdojo** [comment]
@Akshay1018 can you discuss this with the other person and figure it out amongst yourselves?

**Comment by Akshay1018** [comment]
Sure, thanks.
