### ISSUE TITLE
[FEATURE] Make a progress bar

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#262]
### Description

We are going to officially launch the website when we have 100 approved questions.

Until then, we should show a progress bar showing how many of them have been approved on the landing page.

**Comment by ykdojo** [comment]
Yes, I think something like that might work well.

**Comment by jengkhaw95** [comment]
Sounds great! Can I pick up this one? 😁

**Comment by ykdojo** [comment]
of course!

another idea I had is to do it step by step.

for example: get to 10 approved questions to *unlock* something, get to 25 to unlock more, etc.

**Comment by jengkhaw95** [comment]
I like the idea of the multi-step progress bar that unlocks different stuff at each stage!

I will work on a multi-step progress bar.
And also, set a 1 step progress (hard-coded to 'Launch' at 100 approved questions) for now.

Maybe we can figure out **what** to _unlock_ & **where** to store the _milestones_ (hardcode them OR in the database) along the way.

**Comment by ykdojo** [comment]
Sounds perfect! Thank you so much
