### ISSUE TITLE
[FEATURE] Add your coding platform profile while submitting question

### ISSUE THREAD

**Issue by ArkaPrabhaChowdhury** [ykdojo/defaang#285]
### Description

To avoid or reduce spam question submissions which are completely fake, we can add an input tag to the submit question form that asks the user their most used coding platform like Leetcode, CodeChef , GeeksforGeeks and so on. This will allow the admin to check whether the person has legit coding experience or not.

**Comment by ykdojo** [comment]
I don't think this is a good idea because we want the submission process to be as simple as possible and this would add extra friction to it. I think a better approach would be to have a better filtering process by moderators.

**Comment by ArkaPrabhaChowdhury** [comment]
Would the moderators be limited? If not, another suggestion would be to create a login page for moderators. After logging in, the moderators can view the submitted questions. I would love to work on the authentication of the login.

**Comment by ykdojo** [comment]
Yes, that's how it should work.

We have an issue for it already: #75

**Comment by Princeton21** [comment]
@ykdojo  I feel this issue can be closed
