### ISSUE TITLE
[FEATURE] Adding a "sign in" besides "sign up today"

### ISSUE THREAD

**Issue by AryanBabber** [ykdojo/defaang#298]
### Description

There is a "sign up today" button and to make the returning users' experience better, a "sign in" button beside the sign up button (preferably to the left of the sign up button).

**Comment by jeoffreyduke** [comment]
i could work on this

**Comment by AryanBabber** [comment]
Go on then @jeoffreyduke. It's open for all

**Comment by ykdojo** [comment]
I don't think it's necessary to add it there. If people want to sign in, they click the sign up button and click sign in there.
