### ISSUE TITLE
[FEATURE] <Connect it with Supabase>

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#33]
Assuming we go with [Supabase](https://github.com/ykdojo/defaang/discussions/23), we should make a connection to it from our frontend, and document how to set up a SB account/database with it.

For the initial version, we could have something really simple, maybe like a counter? As in, you click a button and the number increases by one, or something like that.

Alternatively, we can set up a user signup/login form as in #14.

**Comment by Trowl3r** [comment]
Hey, 
I would like to take this as my first ticket, if it is still open. If it's okay, I would make a simple signup/ login form wo any big stylings for the start that creates/login the user to Supabase

**Comment by ykdojo** [comment]
Yes! That sounds perfect - thank you so much

**Comment by Trowl3r** [comment]
Just to make it clear: it should make auithenticate the user via supabase, right? Because I am a little confused with  [this issue](https://github.com/ykdojo/defaang/issues/14) right now, but I'll assume this is just for the styling and not for login right? Or did I get something completly wrong?

**Comment by ykdojo** [comment]
Yes, correct. Thank you for clarifying it
