### ISSUE TITLE
[FEATURE] <let's follow semantic commits>

### ISSUE THREAD

**Issue by rohitdasu** [ykdojo/defaang#37]
### Description

As we have started coding, we should use semantic commits. It helps a lot to reviewers who reviews the code, as well as the developer. It builds a good habit which makes us a better developer.

Ref: https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

**Comment by rohitdasu** [comment]
@ykdojo would love to know your opinion on this.

**Comment by ykdojo** [comment]
Yes it seems like a good convention to follow?

**Comment by rohitdasu** [comment]
> Yes it seems like a good convention to follow?

yeah, it will be more readable and we can know what's the commit do at first glance

**Comment by ykdojo** [comment]
@rohitdasu do you have the perm to turn this into an announcement in discussions?

Or maybe you can send a PR to add it to the README?

**Comment by rohitdasu** [comment]
@ykdojo i don't have the perm to turn this into an announcement 😔 
But i will create a PR to add it to README.md file and i think README.MD is better place to keep this 😃

**Comment by ykdojo** [comment]
@rohitdasu sounds good!

Only one suggestion though: I really don't like the "chore" label. I think it's okay to use it from time to time, but a lot of times, it seems like they're really for DX (dev experience) improvements. Can we use *dx* for those?

**Comment by rohitdasu** [comment]
> @rohitdasu sounds good!
> 
> Only one suggestion though: I really don't like the "chore" label. I think it's okay to use it from time to time, but a lot of times, it seems like they're really for DX (dev experience) improvements. Can we use _dx_ for those?

what about keeping both? chore and dx? we can chose what suits better according to the PR / Commit
@ykdojo what's your opinion on this? but i'm open to replace "chore" with "dx" 👍

**Comment by ykdojo** [comment]
@rohitdasu yes keeping both sounds good!

**Comment by rohitdasu** [comment]
cool
