### ISSUE TITLE
Add a new issue template for DX improvements / refactoring

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#44]
DX = developer experience

**Comment by rohitdasu** [comment]
@ykdojo you can assign this to me, i can do it. but lets discuss what fields should be there? are we going to keep it like other templates?

**Comment by ykdojo** [comment]
@rohitdasu keeping it like other templates sounds good.

keep in mind that we have #49 too

**Comment by rohitdasu** [comment]
Sure
