### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by AdityaPainuli** [ykdojo/defaang#45]
### Description

Is this a brand new web application or do you guys implement something into cause when I cloned it . I am seeing a clean project with default screen.. I am new to open source and want to contribute.

**Comment by Preet-Sojitra** [comment]
By clean project you mean no issues and pull requests are showing?

**Comment by ykdojo** [comment]
Yes it is going to be a brand new web app

**Comment by AdityaPainuli** [comment]
yeah ok I got it just pushed my PR for the first time in the project .. let's see what happen
