### ISSUE TITLE
[FEATURE] <Explain this project on the "production site">

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#48]
### Description

We deploy this site to Vercel [here](https://defaang.vercel.app/), but it's just a starter template, and it doesn't say anything about the project.

Some people might be confused about that: #45

It'd be good to explain what this project is about there, even if it's a temporary thing.

**Comment by Swaraj-Singh-30** [comment]
> The developer's project, Dfaang, aims to help them it's users to be well prepared with their interviews. Users of Dfaang can access interview questions used by businesses. Developers remains unknown..... 

Something like this?

**Comment by ykdojo** [comment]
I think what we have in #52 is good for now
