### ISSUE TITLE
[FEATURE] <Better sign up flow>

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#51]
### Description

When a user signs up at /signup, confirming the email is required. I think we should make that clear.

Also, we should probably add some info about how to find the signup page (/signup) and the signin page (/signin) either on the site itself or in README.

**Comment by Trowl3r** [comment]
I would like to take this one on aswell. Little Idea: Maybe make a section with all the current pages in the README with all their corresponding .tsx files, aslong as we don't have a navbar?

**Comment by ykdojo** [comment]
Sounds good! Having a navbar (or any other way of navigation) might be a good solution, also.

**Comment by pushkaraj2007** [comment]
> ### Description
> When a user signs up at /signup, confirming the email is required. I think we should make that clear.
> 
> Also, we should probably add some info about how to find the signup page (/signup) and the signin page (/signin) either on the site itself or in README.

I think we should do that with a npm package called 'nodemailer', for confirming the mail.

What do you think?

**Comment by pushkaraj2007** [comment]
I think we should do that with a package called 'nodemailer', for confirming the mail of users.

What do you think?

**Comment by pushkaraj2007** [comment]
I think we should use a package called 'nodemailer', for confirming the mail of users.

What do you think?

**Comment by ykdojo** [comment]
We're using Supabase right now, but that could definitely be an option maybe with NextAuth.

What would be the pros and cons of that approach?

**Comment by pushkaraj2007** [comment]
> We're using Supabase right now, but that could definitely be an option maybe with NextAuth.
> 
> What would be the pros and cons of that approach?

As of I didn't worked much with supabase.

But if I talk about nodemailer, then I think it's a great library to send emails with ease. 

Where you can send emails with just some lines of code like 15 - 20 and its fast as well.

The fall back is you can only authenticate the user by email. If you want to add other authentication options like google, GitHub then you have to add them by another method.

**Comment by olamide203** [comment]
- We could have a `confirm-email` page which a user gets redirected to from `/signup` on successful signup.
-  The confirm-email page would  inform the user that a mail was sent to them containing a confirmation link.
-  when the user clicks on the link, they would get redirected to the main dashboard by supabase
- also links to `signup` and `signin` pages could be added to the navbar

**Comment by ykdojo** [comment]
> when the user clicks on the link, they would be redirected to the main app dashboard by supabase

I'm not sure what you mean by the main app dashboard by supabase here?

**Comment by olamide203** [comment]
Supabase allows us to define the url a user gets redirected to on email confirmation. We can use that to redirect the user back to the part a user sees after signing in. for now it can just redirect to `\lndex` which is the default

**Comment by ykdojo** [comment]
You meant index (/), right?

**Comment by olamide203** [comment]
yea

**Comment by ykdojo** [comment]
FYI, for the navbar, I created [this separate issue](https://github.com/ykdojo/defaang/issues/122). I think I'm going to work on that one next.
