### ISSUE TITLE
[DOCS] <Improve the documentation>

### ISSUE THREAD

**Issue by subhoghoshX** [ykdojo/defaang#54]
### 

I think the doc can be improve in many ways. 
- Use semantic ordered list for the instructions, instead of `#1` or `#2`
- Remove the comments which are in parentheses. As, if you click on the copy button, they also get copied. Bad UX.
- Add steps like `cd <project-directory>` to remove any confusion

For reference here's how tailwindcss.com does it.

![image](https://user-images.githubusercontent.com/108616679/184506878-a285e5d5-6bb9-4881-b427-dee8a190ae88.png)

It's simple & to the point. Any feedback is welcome.

**Comment by subhoghoshX** [comment]
I'd like to work on it. @ykdojo could you assign me this

**Comment by ykdojo** [comment]
It looks like it didn't show up on the commit history?

**Comment by subhoghoshX** [comment]
Yes, because I discarded the commit and closed the PR. I send another PR.
