### ISSUE TITLE
[FEATURE] <A question submission box> (frontend)

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/defaang#59]
Quoting myself from #10:

> The first step is the signup flow as I mentioned at https://github.com/ykdojo/defaang/issues/14, and then after that, maybe a submission box? We can store them privately for now (probably in Supabase or Firebase), and once we have a few, we can make a view for showing those questions.

This should be possible to implement as we have #33 and #34 implemented already.

**Comment by mark-omarov** [comment]
Hi @ykdojo , how do you imagine the submission box to look like?
Also, what kind of features do you expect it to have? Is there a mockup or some kind of functional spec document?

**Comment by Preet-Sojitra** [comment]
> Hi @ykdojo , how do you imagine the submission box to look like? Also, what kind of features do you expect it to have? Is there a mockup or some kind of functional spec document?

Currently we have this #24

**Comment by ykdojo** [comment]
We should probably have the fields:

- Company (FAANG+, or a custom textbox)
- Location
- Date
- Question
- Question description
- Stay anonymous (check box)

Anything else?

**Comment by Jonyango** [comment]
What if we have a question category? I think it will be good to know what questions are company is mostly focused on.

**Comment by Jonyango** [comment]
Would defaang be focusing on DSA questions, or will it also consist of system design and behavioural questions? @ykdojo

**Comment by ykdojo** [comment]
Having a question category sounds good.

Also forgot: the position name.

**Comment by ykdojo** [comment]
defaang will do both.

but I bet a lot of the questions will cover DSA

**Comment by Jonyango** [comment]
That makes sense.

**Comment by Jonyango** [comment]
If no one is working on this. I would love to take it. I haven't used Typescript before, but I believe I can make this work. Would you please assign this to me?

**Comment by Jonyango** [comment]
@ykdojo Is the position the job title such as software engineer, or is it the levels such as L3?

**Comment by ykdojo** [comment]
The job title. Software Engineer, Site Reliability Engineer, Senior Software Engineer, etc.

**Comment by Jonyango** [comment]
![subscription box](https://user-images.githubusercontent.com/43377714/184556947-59e6e144-ae06-47d9-b691-d0b7d93bb466.PNG)
- This is what I currently have. I am yet to connect it to superbase. Feel free to suggest changes and improvements. @ykdojo @rohitdasu @subhoghoshX @iShibi

**Comment by ykdojo** [comment]
Look good! I think the only required fields should be: Company and Question?

Now that I think about it, I'm not sure if we need the date for it since it'll be recorded anyway.

Maybe instead, it should ask "How recently was this question asked? Within the past: 1 month (default choice)" - and let the user pick any other # of months?

**Comment by Jonyango** [comment]
That sounds okay. I will make the necessary changes.

**Comment by subhoghoshX** [comment]
LGTM. Make sure to add the "stay anonymous" checkbox as well. And I think the Category can also be a dropdown menu.

**Comment by ykdojo** [comment]
@Jonyango I'm not sure where you are on your progress, but I'm thinking of adding my contributions here.

In particular, I'm thinking of:

- Simplifying the submission box somehow
- Making it look good and attractive (and safe) for people to use it

**Comment by ykdojo** [comment]
The required fields:

- Company (FAANG+, or a custom textbox)
- Location
- Date (how long ago was this asked?)
- Question (100 char max?)
- Question details
- Stay anonymous (checkbox)

**Comment by ykdojo** [comment]
On *stay anonymous*, have a tooltip that says something like:

"This question will be associated with your account, but your account will not be shown publicly if this is checked. Later, you'll have an option to un-associate the question from your account completely so it won't even be on record."

**Comment by Jonyango** [comment]
Hey @ykdojo. I made the changes suggested on Sunday, but I haven't made much progress since then(Would get back on this on Friday).  Would you like for me to incorporate the new changes you have suggested? Having some sort of design would be helpful here so that I can recreate it faster. I saw that you pointed @chinaa to help us with the design here.

**Comment by yaa-chi** [comment]
Hi @Jonyango I have actually started with the design. Do check it out here: https://github.com/ykdojo/defaang/issues/82#issuecomment-1219305334

I am currently waiting for everyone to approve of it before We continue to the brand style guide.

**Comment by ykdojo** [comment]
@Jonyango yes! thank you.

Mind keeping us updated on your progress here as you work on it?

That way, I'll know where to potentially jump in, or maybe work on another area of the site, etc.

**Comment by yaa-chi** [comment]
Sure that's fine! @ykdojo I'm currently heading towards the logo design. We're done with color palette for both light and dark mode.

After the logo we're gonna go in with the font, and then finally the website layout for all screens.

**Comment by ykdojo** [comment]
Sounds good! For the website layout, could you keep [Tailwind UI](https://github.com/ykdojo/defaang/discussions/98) in mind as you go about it?

**Comment by yaa-chi** [comment]
Sure I will, both light and dark mode. I think it's better now that we have a direct inspiration of how the website will look like⚡🎉

**Comment by Jonyango** [comment]
> @Jonyango yes! thank you.
> 
> Mind keeping us updated on your progress here as you work on it?
> 
> That way, I'll know where to potentially jump in, or maybe work on another area of the site, etc.

Yes, I will do that.

**Comment by ykdojo** [comment]
@Jonyango just FYI, I think I'm going to try implementing this with [Tailwind UI](https://github.com/ykdojo/defaang/discussions/98) - in particular this one called [simple stacked](https://tailwindui.com/components/application-ui/forms/form-layouts#component-30dffb06e58cdbe872820ed3f943d85a).

I'll keep updating this thread as I produce code so we don't duplicate work.

**Comment by ykdojo** [comment]
I just got [the Application UI package](https://tailwindui.com/components#product-application-ui)!

Let me know if anyone wants to use any of the components.

**Comment by yaa-chi** [comment]
> I just got [the Application UI package](https://tailwindui.com/components#product-application-ui)!
> 
> Let me know if anyone wants to use any of the components.

Really? The premium one?😍

**Comment by ykdojo** [comment]
This one: <img width="547" alt="image" src="https://user-images.githubusercontent.com/1811651/185665984-76ddede7-a24d-463a-bcd7-7f50e086088a.png">
https://tailwindui.com/components#pricing

**Comment by ykdojo** [comment]
I have a draft PR here - feel free to work off of it if anyone feels like it while I'm away: https://github.com/ykdojo/defaang/pull/105

**Comment by yaa-chi** [comment]
> I have a draft PR here - feel free to work off of it if anyone feels like it while I'm away: #105

YK please what's a draft PR😂😂

**Comment by ykdojo** [comment]
It's just a way to show your code changes, but you're not to have it be reviewed!

**Comment by yaa-chi** [comment]
oh ok, that's great! Github is really cool I'm learning a lot!

**Comment by Jonyango** [comment]
@ykdojo, I am closing the draft PR I raised for this and will try to contribute to the one you have raised.

**Comment by Jonyango** [comment]
So I didn't have to close it. I am confused as to why it shows that it was merged.

**Comment by ykdojo** [comment]
> So I didn't have to close it. I am confused as to why it shows that it was merged.

That's kinda strange and I know GitHub does that sometimes - don't worry about it, though!

**Comment by ykdojo** [comment]
Also I just renamed this to only include frontend. Made a new issue for the backend here: https://github.com/ykdojo/defaang/issues/108

**Comment by ykdojo** [comment]
@Jonyango any updates? If not, I'm thinking of continuing my work on #105

**Comment by ykdojo** [comment]
Moved it to #126 for simplicity (I had some rebasing issues)

**Comment by ykdojo** [comment]
Made a separate issue for styling at #127.

**Comment by Jonyango** [comment]
> @Jonyango, any updates? If not, I'm thinking of continuing my work on #105

Hey. You can continue your work at #105. Life has gotten in the way, and I won't be able to get to it for a while.
