### ISSUE TITLE
[CI] Add Conventional changelog action

### ISSUE THREAD

**Issue by Pradumnasaraf** [ykdojo/defaang#6]
### Changes
- Add workflow for that which create auto-release and CHANGELOG file.
Refer to this - https://github.com/TriPSs/conventional-changelog-action

**Comment by Aryan-Deshpande** [comment]
Hey, I would like to work on this issue!

**Comment by Pradumnasaraf** [comment]
> Hey, I would like to work on this issue!

Yes go ahead :)

**Comment by Aryan-Deshpande** [comment]
Hey, I have just created a pr. Let me know if there is any feedback! would love to learn.

**Comment by ykdojo** [comment]
I'm not too familiar with this actually - @Pradumnasaraf, mind taking a look?

**Comment by Pradumnasaraf** [comment]
> I'm not too familiar with this actually - @Pradumnasaraf, mind taking a look?

Sure!

**Comment by Pradumnasaraf** [comment]
Fixed in https://github.com/ykdojo/defaang/pull/25
