### ISSUE TITLE
[DX] <Add a Contriubting.md file explaining all the contributing guidelines>

### ISSUE THREAD

**Issue by Sadeedpv** [ykdojo/defaang#71]
### Description

Try to add a contriubting.md file explaining all the contributing guidelines.

**Comment by ykdojo** [comment]
changed the title label from FEATURE -> DX btw

**Comment by Caesarsage** [comment]
anyone working on this already ?

**Comment by jideabdqudus** [comment]
> anyone working on this already ?

I am

**Comment by Caesarsage** [comment]
Alright 👍

**Comment by jideabdqudus** [comment]
There's now an Open PR that fixes this issue: https://github.com/ykdojo/defaang/pull/78
