### ISSUE TITLE
[DX] Github action for deployment 

### ISSUE THREAD

**Issue by Dun-sin** [ykdojo/defaang#76]
### Description

**_Problem_**: Right now every pull request tries to get deployed to production by vercel, but we don't want this

**_Solution_**: create a Github action to automate deployment only if the pull request has been merged

**_Related Discussion_**:The Vercel bot started acting out and keeps asking me to authorize some stuff:

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/1811651/184505420-c98d3c61-dbf3-42ba-8992-409914ca094d.png">

We should probably contact them and ask them what's going on, or I'll look into it some more.

_Originally posted by @ykdojo in https://github.com/ykdojo/defaang/discussions/56_

**Comment by iShibi** [comment]
This is just vercel trying to be secure by default and it can be fixed by turning off [git-fork-protection](https://vercel.com/docs/concepts/projects/overview#git-fork-protection) in the project settings:

![vercel](https://user-images.githubusercontent.com/51517103/184562138-89dfbd0a-2d4f-43bf-8e94-3b77646fad4f.png)

@ykdojo

**Comment by ykdojo** [comment]
Hmm interesting. Do you think it's safe to turn it off @iShibi?

**Comment by iShibi** [comment]
If you have set secrets in `Environment Variables` on vercel then I'll say keep it enabled and allow it to run on each PR after checking its changes. This would be time consuming but a safer option.

**Comment by Dun-sin** [comment]
If you want to look at a similar Github action [here it is](https://github.com/Dun-sin/trick-generator/blob/main/.github/workflows/deployment.yml)

**Comment by ykdojo** [comment]
@Dun-sin hmm when something is merged into main, it's already deployed into the main Vercel instance. So I'm not sure if that's necessary actually

**Comment by iShibi** [comment]
> If you want to look at a similar Github action [here it is](https://github.com/Dun-sin/trick-generator/blob/main/.github/workflows/deployment.yml)

It's not about automating. The said GitHub action will do the same thing that vercel is doing currently. It's about securing secrets stored in the environment variable. Someone can open a PR to get those secrets and we will be too late to do anything as the CI will build it automatically. On per PR basis we can first check that the PR is not doing anything with the secrets and then authorize the build.

**Comment by Dun-sin** [comment]
> @Dun-sin hmm when something is merged into main, it's already deployed into the main Vercel instance. So I'm not sure if that's necessary actually

I know, personally I thought the issue to the bot giving those warnings is because it was getting from a branch.

So I created a Github action to make vercel not deploy in any branch unless it's the main one.

It fixed the issue without me having to turn off the protection in vercel itself

**Comment by ykdojo** [comment]
Ah I see.

Still from my perspective, it is really convenient to be able to review the changes on a Vercel instance. As you mentioned, it's good for reviewing things visually

**Comment by Dun-sin** [comment]
> Ah I see.
> 
> Still from my perspective, it is really convenient to be able to review the changes on a Vercel instance. As you mentioned, it's good for reviewing things visually

Yes, it doesn't take away the preview part of things. Just holds up the actual deployment until merged into main
