### ISSUE TITLE
[FEATURE] add GitPod button to README.md file

### ISSUE THREAD

**Issue by RakeshSangem** [ykdojo/defaang#84]
### Description

Setting up the project on a local machine is never fun. So I recently learned about GitPod, a pretty great service that allows us to work and contribute to projects directly from the browser.

Therefore, I want to include the GitPod button in this project.

**Comment by ykdojo** [comment]
Sounds good! I don't think it's by GitHub though. I think it's an independent company

**Comment by RakeshSangem** [comment]
My mistake—I mistakenly believed it to be from GitHub.
I appreciate you letting me know.

**Comment by mark-omarov** [comment]
I believe [GitHub Codespaces](https://github.com/features/codespaces) is similar to that.
It's fine by me, as long as it's not enforced, not every developer would like to use a VSCode-based editor, even if it's in the cloud. I'd prefer to keep my WebStorm around, for example. 😄

**Comment by ykdojo** [comment]
I think it's this one: https://github.com/ykdojo/defaang/pull/102

**Comment by veganaize** [comment]
Is this completed & waiting for others to review or should it be moved back to "In Progress" @RakeshSangem ?

**Comment by RakeshSangem** [comment]
Yes, there are some problems with prettier. I was unable to complete it because of my exams. You can either mark this PR as "In progress" or close it for the time being.

**Comment by veganaize** [comment]
I don't have the ability to move anything on this board.  Can someone who does please move this to the "Later" or "To do" column?  _Thanks._

**Comment by ykdojo** [comment]
I'm just going to close it.
