### ISSUE TITLE
[DOCS] Complete all community guidelines 

### ISSUE THREAD

**Issue by rohitdasu** [ykdojo/defaang#89]
### Description

Let's add missing docs.

https://github.com/ykdojo/defaang/community

<img width="953" alt="Screenshot 2022-08-15 at 10 42 25 PM" src="https://user-images.githubusercontent.com/48400770/184683099-2d3c5278-0954-4376-bffc-e4ed15d87092.png">

**Comment by iShibi** [comment]
Reopening this because #78 is yet to be merged.

**Comment by veganaize** [comment]
Somebody should probably drag this back under "In progress"...?

**Comment by rohitdasu** [comment]
done! thanks @veganaize
